## Numpy
#### Numpy is a general purpose array-processing package in python

In [1]:
import numpy as np
#1d array from a python list
arr1d = np.array([1,2,3,4,5])
arr1d

array([1, 2, 3, 4, 5])

In [2]:
#2d array from a nested python list
arr2d = np.array([[1,2,3],[4,5,6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
zeros_arr = np.zeros((3,4))
print(zeros_arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Array attributes

In [4]:
#shape
shape = arr2d.shape
print(shape)

(2, 3)


In [6]:
#size
size = arr2d.size
print(size)

6


In [7]:
zeros_arr.size

12

In [8]:
#data type
data_type = arr2d.dtype
print(data_type)

int32


In [9]:
zeros_arr.dtype

dtype('float64')

In [10]:
print(arr2d)

[[1 2 3]
 [4 5 6]]


### Array Operations

In [11]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
#addition
addition = 2 + arr2d
print(addition)

[[3 4 5]
 [6 7 8]]


In [13]:
#subtraction
subtraction = arr2d - 3
print(subtraction)

[[-2 -1  0]
 [ 1  2  3]]


In [14]:
#Multiplication
multiplication = 4 * arr2d
print(multiplication)

[[ 4  8 12]
 [16 20 24]]


### Aggregation Functions

In [15]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
#sum
total_sum = arr2d.sum()
print(total_sum)

21


In [17]:
#max
max_val = arr2d.max()
print(max_val)

6


In [18]:
#min
min_val = arr2d.min()
print(min_val)

1


### Indexing

In [19]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
#second row
second_row = arr2d[1:,:]
print(second_row)

[[4 5 6]]


In [21]:
#first row
first_row = arr2d[0:1,:]
print(first_row)

[[1 2 3]]


In [22]:
second_row_element = arr2d[1:,1:]
print(second_row_element)

[[5 6]]


In [23]:
first_row_element = arr2d[0:1,0:2]
print(first_row_element)

[[1 2]]


In [24]:
first_row_ = arr2d[0:1,1:]
print(first_row_)

[[2 3]]


In [25]:
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [26]:
first_row_ = arr2d[0,1:]
print(first_row_)

[2 3]


In [27]:
first_row_ = arr2d[:1,1:]
print(first_row_)

[[2 3]]


In [28]:
first_row_ = arr2d[0,1:]
print(first_row_)

[2 3]


### Array Manipulation

In [29]:
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [31]:
arr2d.shape

(2, 3)

In [32]:
#reshape
reshaped_arr = arr2d.reshape(3,2)
print(reshaped_arr)

[[1 2]
 [3 4]
 [5 6]]


In [33]:
reshaped_arr1 = arr2d.reshape(1,6)
print(reshaped_arr1)

[[1 2 3 4 5 6]]


In [35]:
#Concatenate Arrays
arr1d = [1,2,3]
concat_arr = np.concatenate([arr1d,arr1d])
print(concat_arr)

[1 2 3 1 2 3]


In [36]:
#append
arr1d = np.array([1,2,3])
append_arr = np.append(arr1d,[4,5,6])
print(append_arr)

[1 2 3 4 5 6]


In [37]:
#append to 2 dimensional array
arr2d = np.array([[1,2,3],[4,5,6]])
append_arr1 = np.append(arr2d,[7,8,9])
print(append_arr1)

[1 2 3 4 5 6 7 8 9]


## Question asked

### Can you append a row ([4,5,6]) to the array [1,2,3], so it looks like this [[1,2,3],[4,5,6]] rather than this: [1,2,3,4,5,6]?

### Answer: To achieve that, both arrays need to be two-dimensional arrays.

In [38]:
#Answer to question asked
arr1d = np.array([[1,2,3]])
concat_arr2 = np.concatenate([arr1d,np.array([[4,5,6]])])
print(concat_arr2)

[[1 2 3]
 [4 5 6]]


### Broadcasting

In [39]:
#broadcasting
a = np.array([1,2,3])
b = 4
print(a+b)

[5 6 7]


In [40]:
a = np.array([1,2,3])
b = 6
print(a*b)

[ 6 12 18]


In [41]:
a = np.array([1,2,3])
print(4 + a)

[5 6 7]


### Random Number Generation

In [43]:
random_numbers = np.random.rand(3,3)
print(random_numbers)   #generates numbers from a uniform distribution between 0 and 1.

[[0.75697305 0.0804393  0.5177853 ]
 [0.77385264 0.26150189 0.46198486]
 [0.77143484 0.18834364 0.80148618]]


In [44]:
random_numbers = np.random.rand(4,6)
print(random_numbers)

[[0.83007688 0.7432273  0.24291072 0.57967094 0.15994472 0.29170538]
 [0.14103882 0.84111761 0.66940518 0.51313474 0.03632015 0.83173165]
 [0.70282596 0.57822557 0.75174324 0.29822001 0.17320915 0.22644956]
 [0.6135717  0.58058785 0.43447489 0.91249328 0.52634217 0.85126294]]


In [45]:
random_numbers_ = np.random.randint(0,100,6)
print(random_numbers_)

[37 19 21 66 97 35]


In [46]:
random_numbers_ = np.random.randint(0,100,6).reshape(3,2)
print(random_numbers_)

[[60 10]
 [25 91]
 [34 44]]


In [47]:
random_numbers1 = np.random.randn(4, 7)
print(random_numbers1)

[[ 0.78448571  1.04063123 -1.10399804 -0.50640614 -1.26808273 -1.60280362
  -0.08050927]
 [-0.87343295 -0.28834029 -0.12229317 -0.41912961  0.65858469 -0.5607674
  -0.48908902]
 [-1.1533156  -1.08387636 -0.3457478   1.14328493 -1.15157548  0.80024831
   1.12290033]
 [-0.49576154 -0.58269078 -0.125482    1.31889408 -0.48108913  0.7559355
  -1.84791304]]


In [48]:
items = np.array (["A", "B", "C", "D"])
items

array(['A', 'B', 'C', 'D'], dtype='<U1')

In [49]:
random_numbers2 = np.random.choice(items, 3)
print(random_numbers2)

['B' 'C' 'C']


## Linear Algebra

In [50]:
# Matrix Addition
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
A, B

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [51]:
print(A + B)

[[ 6  8]
 [10 12]]


In [52]:
#Matrix Subtraction
print(A - B)

[[-4 -4]
 [-4 -4]]


In [53]:
#Matrix Multiplication (Element-wise multiplication)
print(A * B)

[[ 5 12]
 [21 32]]


In [54]:
#Matrix Multiplication
print(A @ B)

[[19 22]
 [43 50]]


In [55]:
result = np.matmul(A,B)
print(result)

[[19 22]
 [43 50]]


In [56]:
#Matrix Multiplication (Column-wise)
print(A * B)

[[ 5 12]
 [21 32]]


In [57]:
# Standard Matrix multiplication
F = np.dot(A,B)
print(F)

[[19 22]
 [43 50]]


In [58]:
A

array([[1, 2],
       [3, 4]])

In [59]:
#Transpose of a matrix
transpose_A = np.transpose(A)
print(transpose_A)

[[1 3]
 [2 4]]


In [60]:
#Inverse of a matrix
A_inv = np.linalg.inv(A)
print(A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [61]:
#Inverse of a matrix
B_inv = np.linalg.inv(B)
print(B_inv)

[[-4.   3. ]
 [ 3.5 -2.5]]


In [69]:
#identity Matrix
identity_matrix = np.eye(4)
print(identity_matrix)  # has 1s on the main diagonal and 0s everywhere else

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [63]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [64]:
B

array([[5, 6],
       [7, 8]])

In [68]:
#determinant of a matrix
determinant = np.linalg.det(B)
print(round(np.linalg.det(B)))

-2


## Delete elements in an array

In [70]:
arr = np.array([1,2,3,4,5])
arr_deleted = np.delete(arr,2)
print(arr_deleted)

[1 2 4 5]


In [71]:
club_arr = np.array(['Madrid','Barcelona','Arsenal','Dortmund','PSG','Mancity'])
arr_deleted = np.delete(club_arr,[1,2])
print(arr_deleted)

['Madrid' 'Dortmund' 'PSG' 'Mancity']


In [72]:
arr = np.array([1,2,3,4,5])
m = arr != 5
new_arr = arr[m]
print(new_arr)

[1 2 3 4]


### To make sure that the elements that are removed in arr_deleted are also deleted in club_arr

In [73]:
club_arr = np.array(['Madrid','Barcelona','Arsenal','Dortmund','PSG','Mancity'])
arr_deleted = np.delete(club_arr,[1,2])
club_arr = arr_deleted
print(club_arr)

['Madrid' 'Dortmund' 'PSG' 'Mancity']


## Statistical Functions

In [74]:
arr = np.array([1,2,3,4,5])

In [75]:
#mean
arr_mean = np.mean(arr)
print(arr_mean)

3.0


In [76]:
#median
arr_median = np.median(arr)
print(arr_median)

3.0


In [78]:
arr_1 = np.array([1,2,3,4,5,6])

In [79]:
arr1_median = np.median(arr_1)
print(arr1_median)

3.5


In [80]:
#Mode : numpy does not have the mode method, so scipy can be used
arr_ = np.array([1,2,2,3,4,5,6])
from scipy import stats
arr_mode = stats.mode(arr_,keepdims = False)
print(arr_mode)

ModeResult(mode=2, count=2)


In [81]:
#standard deviation
arr_std = np.std(arr)
print(arr_std)

1.4142135623730951
